import test from "node:test";
import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import { chunk, createBetterScrapersController, isRateLimited } from "../src/controller.js";

function setup(url="https://cove.local/videos?view=tagger",options={}){
  const dom=new JSDOM(`<!doctype html><html><head></head><body><button id="global-search"><svg class="lucide-search"></svg></button><main><div id="toolbar"><button id="original">Scrape All</button><span>3 videos</span></div><div class="divide-y divide-border"><div class="border-b" data-testid="tagger-row"><button class="search"><svg class="lucide-search"></svg></button><button class="save">Save</button></div><div class="border-b" data-testid="tagger-row"><button class="search"><svg class="lucide-search"></svg></button></div><div class="border-b" data-testid="tagger-row"><button class="search"><svg class="lucide-search"></svg></button></div></div></main></body></html>`,{url});
  const controller=createBetterScrapersController({document:dom.window.document,location:dom.window.location,MutationObserver:dom.window.MutationObserver,settingsProvider:options.settingsProvider||(async()=>({batchSize:2,pauseSeconds:0})),delay:options.delay});
  return {dom,controller,document:dom.window.document};
}

test("chunk splits work into configured batches",()=>assert.deepEqual(chunk([1,2,3,4,5],2),[[1,2],[3,4],[5]]));
test("recognizes both numeric and textual rate limits",()=>{assert.equal(isRateLimited(new Error("HTTP 429")),true);assert.equal(isRateLimited(new Error("Too many requests")),true);assert.equal(isRateLimited(new Error("Server failed")),false);});
test("injects native-styled, equal-height controls and hides original",()=>{const {controller,document}=setup();controller.start();const scrape=document.querySelector('[data-action="scrape"]'),save=document.querySelector('[data-action="save"]');assert.equal(save.textContent,"Save All");assert.match(scrape.className,/bg-accent/);assert.match(save.className,/bg-green-600/);assert.ok(scrape.classList.contains("py-1"));assert.ok(save.classList.contains("py-1"));assert.ok(!save.classList.contains("py-1.5"));assert.ok(scrape.querySelector("svg.lucide-cloud-download"));assert.ok(save.querySelector("svg.lucide-check"));assert.equal(document.getElementById("original").style.display,"none");controller.stop();});
test("does not attach outside tagger view",()=>{const {controller,document}=setup("https://cove.local/videos?view=grid");controller.start();assert.equal(document.getElementById("better-scrapers-controls"),null);controller.stop();});
test("scrape all waits for a batch and never opens global search",async()=>{const {controller,document}=setup();let active=0,maxActive=0,globalClicks=0;document.getElementById("global-search").addEventListener("click",()=>globalClicks++);for(const button of document.querySelectorAll(".search")){button.addEventListener("click",()=>{button.disabled=true;active++;maxActive=Math.max(maxActive,active);setTimeout(()=>{active--;button.disabled=false;},10);});}controller.start();document.querySelector('[data-action="scrape"]').click();await waitFor(()=>/Scrape complete/.test(document.querySelector('[role="status"]').textContent));assert.equal(maxActive,2);assert.equal(globalClicks,0);assert.match(document.querySelector('[role="status"]').textContent,/3 succeeded/);controller.stop();});
test("save all saves ready selections",async()=>{const {controller,document}=setup();const save=document.querySelector(".save");save.addEventListener("click",()=>setTimeout(()=>{save.closest(".border-b").append("Saved successfully");save.remove();},5));controller.start();document.querySelector('[data-action="save"]').click();await waitFor(()=>/1 saved/.test(document.querySelector('[role="status"]').textContent));controller.stop();});
test("retries 429s at an exponential cap before advancing",async()=>{const pauses=[],order=[];const {controller,document}=setup("https://cove.local/videos?view=tagger",{settingsProvider:async()=>({batchSize:1,pauseSeconds:5,useBackoff:true,maximumBackoff:15}),delay:async milliseconds=>pauses.push(milliseconds)});const searches=[...document.querySelectorAll(".search")];searches[2].disabled=true;let firstClicks=0;searches[0].addEventListener("click",()=>{firstClicks++;order.push(`first-${firstClicks}`);const row=searches[0].closest(".border-b");row.querySelector(".text-red-400")?.remove();searches[0].disabled=true;setTimeout(()=>{if(firstClicks<3){const error=document.createElement("p");error.className="text-red-400";error.textContent="Response status code does not indicate success: 429 (Too Many Requests).";row.appendChild(error);}searches[0].disabled=false;},5);});searches[1].addEventListener("click",()=>{order.push("second");searches[1].disabled=true;setTimeout(()=>searches[1].disabled=false,5);});controller.start();document.querySelector('[data-action="scrape"]').click();await waitFor(()=>/Scrape complete: 2 succeeded/.test(document.querySelector('[role="status"]').textContent));assert.deepEqual(order,["first-1","first-2","first-3","second"]);assert.deepEqual(pauses,[10000,15000,5000]);controller.stop();});
async function waitFor(predicate){const start=Date.now();while(!predicate()){if(Date.now()-start>2000)throw new Error("test timeout");await new Promise(resolve=>setTimeout(resolve,10));}}
