<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Cove.BetterScrapers</AssemblyName>
    <RootNamespace>Cove.BetterScrapers</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="extension.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
    <None Include="dist\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalCovePlugins)' == 'false'">
    <PackageReference Include="Cove.Plugins" Version="$(CovePluginsVersion)"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalCovePlugins)' == 'true'">
    <ProjectReference Include="$(CoveSourceRoot)\src\Cove.Core\Cove.Core.csproj"><Private>false</Private><ExcludeAssets>runtime</ExcludeAssets></ProjectReference>
    <ProjectReference Include="$(CoveSourceRoot)\src\Cove.Plugins\Cove.Plugins.csproj"><Private>false</Private><ExcludeAssets>runtime</ExcludeAssets></ProjectReference>
    <ProjectReference Include="$(CoveSourceRoot)\src\Cove.Sdk\Cove.Sdk.csproj"><Private>false</Private><ExcludeAssets>runtime</ExcludeAssets></ProjectReference>
  </ItemGroup>
  <Import Project="$(CoveSourceRoot)\src\Cove.Sdk\buildTransitive\Cove.Sdk.targets" Condition="'$(UseLocalCovePlugins)' == 'true'" />
</Project>
